#[derive(Debug, Clone, PartialEq)]
pub enum BoxType {
    Ftyp,
    Pdin,
    Moov,
    Mvhd,
    Meta,
    Trak,
    Tkhd,
    Tref,
    Trgr,
    Edts,
    Elst,
    Mdia,
    Mdhd,
    Hdlr,
    Elng,
    Minf,
    Vmhd,
    Smhd,
    Hmhd,
    Sthd,
    Nmhd,
    Dinf,
    Dref,
    Stbl,
    Stsd,
    Stts,
    Ctts,
    Cslg,
    Stsc,
    Stsz,
    Stz2,
    Stco,
    Co64,
    Stss,
    Stsh,
    Padb,
    Stdp,
    Sdtp,
    Sbgp,
    Sgpd,
    Subs,
    Saiz,
    Saio,
    Udta,
    Mvex,
    Mehd,
    Trex,
    Leva,
    Moof,
    Mfhd,
    Traf,
    Tfhd,
    Trun,
    Tfdt,
    Mfra,
    Tfra,
    Mfro,
    Mdat,
    Free,
    Skip,
    Cprt,
    Tsel,
    Strk,
    Stri,
    Strd,
    Iloc,
    Ipro,
    Sinf,
    Frma,
    Schm,
    Schi,
    Iinf,
    Xml,
    Bxml,
    Pitm,
    Fiin,
    Paen,
    Fire,
    Fpar,
    Fecr,
    Segr,
    Gitn,
    Idat,
    Iref,
    Meco,
    Mere,
    Styp,
    Sidx,
    Ssix,
    Prft,
    Unknown([u8; 4]),
}

impl From<[u8; 4]> for BoxType {
    fn from(value: [u8; 4]) -> Self {
        match &value {
            b"ftyp" => BoxType::Ftyp,
            b"pdin" => BoxType::Pdin,
            b"moov" => BoxType::Moov,
            b"mvhd" => BoxType::Mvhd,
            b"meta" => BoxType::Meta,
            b"trak" => BoxType::Trak,
            b"tkhd" => BoxType::Tkhd,
            b"tref" => BoxType::Tref,
            b"trgr" => BoxType::Trgr,
            b"edts" => BoxType::Edts,
            b"elst" => BoxType::Elst,
            b"mdia" => BoxType::Mdia,
            b"mdhd" => BoxType::Mdhd,
            b"hdlr" => BoxType::Hdlr,
            b"elng" => BoxType::Elng,
            b"minf" => BoxType::Minf,
            b"vmhd" => BoxType::Vmhd,
            b"smhd" => BoxType::Smhd,
            b"hmhd" => BoxType::Hmhd,
            b"sthd" => BoxType::Sthd,
            b"nmhd" => BoxType::Nmhd,
            b"dinf" => BoxType::Dinf,
            b"dref" => BoxType::Dref,
            b"stbl" => BoxType::Stbl,
            b"stsd" => BoxType::Stsd,
            b"stts" => BoxType::Stts,
            b"ctts" => BoxType::Ctts,
            b"cslg" => BoxType::Cslg,
            b"stsc" => BoxType::Stsc,
            b"stsz" => BoxType::Stsz,
            b"stz2" => BoxType::Stz2,
            b"stco" => BoxType::Stco,
            b"co64" => BoxType::Co64,
            b"stss" => BoxType::Stss,
            b"stsh" => BoxType::Stsh,
            b"padb" => BoxType::Padb,
            b"stdp" => BoxType::Stdp,
            b"sdtp" => BoxType::Sdtp,
            b"sbgp" => BoxType::Sbgp,
            b"sgpd" => BoxType::Sgpd,
            b"subs" => BoxType::Subs,
            b"saiz" => BoxType::Saiz,
            b"saio" => BoxType::Saio,
            b"udta" => BoxType::Udta,
            b"mvex" => BoxType::Mvex,
            b"mehd" => BoxType::Mehd,
            b"trex" => BoxType::Trex,
            b"leva" => BoxType::Leva,
            b"moof" => BoxType::Moof,
            b"mfhd" => BoxType::Mfhd,
            b"traf" => BoxType::Traf,
            b"tfhd" => BoxType::Tfhd,
            b"trun" => BoxType::Trun,
            b"tfdt" => BoxType::Tfdt,
            b"mfra" => BoxType::Mfra,
            b"tfra" => BoxType::Tfra,
            b"mfro" => BoxType::Mfro,
            b"mdat" => BoxType::Mdat,
            b"free" => BoxType::Free,
            b"skip" => BoxType::Skip,
            b"cprt" => BoxType::Cprt,
            b"tsel" => BoxType::Tsel,
            b"strk" => BoxType::Strk,
            b"stri" => BoxType::Stri,
            b"strd" => BoxType::Strd,
            b"iloc" => BoxType::Iloc,
            b"ipro" => BoxType::Ipro,
            b"sinf" => BoxType::Sinf,
            b"frma" => BoxType::Frma,
            b"schm" => BoxType::Schm,
            b"schi" => BoxType::Schi,
            b"iinf" => BoxType::Iinf,
            b"xml " => BoxType::Xml,
            b"bxml" => BoxType::Bxml,
            b"pitm" => BoxType::Pitm,
            b"fiin" => BoxType::Fiin,
            b"paen" => BoxType::Paen,
            b"fire" => BoxType::Fire,
            b"fpar" => BoxType::Fpar,
            b"fecr" => BoxType::Fecr,
            b"segr" => BoxType::Segr,
            b"gitn" => BoxType::Gitn,
            b"idat" => BoxType::Idat,
            b"iref" => BoxType::Iref,
            b"meco" => BoxType::Meco,
            b"mere" => BoxType::Mere,
            b"styp" => BoxType::Styp,
            b"sidx" => BoxType::Sidx,
            b"ssix" => BoxType::Ssix,
            b"prft" => BoxType::Prft,
            _ => BoxType::Unknown(value),
        }
    }
}

impl From<&BoxType> for [u8; 4] {
    fn from(value: &BoxType) -> Self {
        match value {
            BoxType::Ftyp => *b"ftyp",
            BoxType::Pdin => *b"pdin",
            BoxType::Moov => *b"moov",
            BoxType::Mvhd => *b"mvhd",
            BoxType::Meta => *b"meta",
            BoxType::Trak => *b"trak",
            BoxType::Tkhd => *b"tkhd",
            BoxType::Tref => *b"tref",
            BoxType::Trgr => *b"trgr",
            BoxType::Edts => *b"edts",
            BoxType::Elst => *b"elst",
            BoxType::Mdia => *b"mdia",
            BoxType::Mdhd => *b"mdhd",
            BoxType::Hdlr => *b"hdlr",
            BoxType::Elng => *b"elng",
            BoxType::Minf => *b"minf",
            BoxType::Vmhd => *b"vmhd",
            BoxType::Smhd => *b"smhd",
            BoxType::Hmhd => *b"hmhd",
            BoxType::Sthd => *b"sthd",
            BoxType::Nmhd => *b"nmhd",
            BoxType::Dinf => *b"dinf",
            BoxType::Dref => *b"dref",
            BoxType::Stbl => *b"stbl",
            BoxType::Stsd => *b"stsd",
            BoxType::Stts => *b"stts",
            BoxType::Ctts => *b"ctts",
            BoxType::Cslg => *b"cslg",
            BoxType::Stsc => *b"stsc",
            BoxType::Stsz => *b"stsz",
            BoxType::Stz2 => *b"stz2",
            BoxType::Stco => *b"stco",
            BoxType::Co64 => *b"co64",
            BoxType::Stss => *b"stss",
            BoxType::Stsh => *b"stsh",
            BoxType::Padb => *b"padb",
            BoxType::Stdp => *b"stdp",
            BoxType::Sdtp => *b"sdtp",
            BoxType::Sbgp => *b"sbgp",
            BoxType::Sgpd => *b"sgpd",
            BoxType::Subs => *b"subs",
            BoxType::Saiz => *b"saiz",
            BoxType::Saio => *b"saio",
            BoxType::Udta => *b"udta",
            BoxType::Mvex => *b"mvex",
            BoxType::Mehd => *b"mehd",
            BoxType::Trex => *b"trex",
            BoxType::Leva => *b"leva",
            BoxType::Moof => *b"moof",
            BoxType::Mfhd => *b"mfhd",
            BoxType::Traf => *b"traf",
            BoxType::Tfhd => *b"tfhd",
            BoxType::Trun => *b"trun",
            BoxType::Tfdt => *b"tfdt",
            BoxType::Mfra => *b"mfra",
            BoxType::Tfra => *b"tfra",
            BoxType::Mfro => *b"mfro",
            BoxType::Mdat => *b"mdat",
            BoxType::Free => *b"free",
            BoxType::Skip => *b"skip",
            BoxType::Cprt => *b"cprt",
            BoxType::Tsel => *b"tsel",
            BoxType::Strk => *b"strk",
            BoxType::Stri => *b"stri",
            BoxType::Strd => *b"strd",
            BoxType::Iloc => *b"iloc",
            BoxType::Ipro => *b"ipro",
            BoxType::Sinf => *b"sinf",
            BoxType::Frma => *b"frma",
            BoxType::Schm => *b"schm",
            BoxType::Schi => *b"schi",
            BoxType::Iinf => *b"iinf",
            BoxType::Xml => *b"xml ",
            BoxType::Bxml => *b"bxml",
            BoxType::Pitm => *b"pitm",
            BoxType::Fiin => *b"fiin",
            BoxType::Paen => *b"paen",
            BoxType::Fire => *b"fire",
            BoxType::Fpar => *b"fpar",
            BoxType::Fecr => *b"fecr",
            BoxType::Segr => *b"segr",
            BoxType::Gitn => *b"gitn",
            BoxType::Idat => *b"idat",
            BoxType::Iref => *b"iref",
            BoxType::Meco => *b"meco",
            BoxType::Mere => *b"mere",
            BoxType::Styp => *b"styp",
            BoxType::Sidx => *b"sidx",
            BoxType::Ssix => *b"ssix",
            BoxType::Prft => *b"prft",
            BoxType::Unknown(v) => *v,
        }
    }
}
