[package]
name = "mediumi-crypto"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "media encryption"
readme = "README.md"
repository.workspace = true
license = "MIT"
keywords = ["multimedia", "cryptography"]
categories = ["multimedia", "cryptography"]

[dependencies]
mediumi-mp4 = { path = "../mediumi-mp4" }
mediumi-h264 = { path = "../mediumi-h264" }
mediumi-util = { path = "../mediumi-util" }
aes = "0.9"
ctr = "0.10"
cbc = "0.2"
